version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  back:
    image: matasvaitk/the-block-back:latest
    environment:
      REDIS_SERVER: redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  front:
    image: matasvaitk/the-block-front:latest
    environment:
      BACKEND_API_URL: http://back
      CLIENT_API_URL: http://13.60.15.233
    depends_on:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back
