name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      DOCKER_COMPOSE_URL: ${{ secrets.DOCKER_COMPOSE_URL }}
      COMPOSE_FILE_URL: ${{ secrets.COMPOSE_FILE_URL }}
      NGINX_CONF_URL: ${{ secrets.NGINX_CONF_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change to Terraform directory
      run: cd terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.7.5'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var="docker_compose_url=${{ env.DOCKER_COMPOSE_URL }}" \
                       -var="compose_file_url=${{ env.COMPOSE_FILE_URL }}" \
                       -var="nginx_conf_url=${{ env.NGINX_CONF_URL }}" \
                       -out=plan.out
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.plan.outcome == 'success'
      run: |
        terraform apply -auto-approve -var="docker_compose_url=${{ env.DOCKER_COMPOSE_URL }}" \
                                      -var="compose_file_url=${{ env.COMPOSE_FILE_URL }}" \
                                      -var="nginx_conf_url=${{ env.NGINX_CONF_URL }}"
