name: 'Setup and Deploy Terraform Infrastructure'

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  DOCKER_COMPOSE_URL: ${{ secrets.DOCKER_COMPOSE_URL }}
  COMPOSE_FILE_URL: ${{ secrets.COMPOSE_FILE_URL }}
  NGINX_CONF_URL: ${{ secrets.NGINX_CONF_URL }}

jobs:
  create_terraform_backend:
    runs-on: ubuntu-latest
    outputs:
      backend-setup: ${{ steps.backend-setup.outcome }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Run setup script for Terraform backend
      id: backend-setup
      run: |
        chmod +x ./terraform/scripts/create-tf-backend.sh
        ./terraform/scripts/create-tf-backend.sh

  deploy_terraform:
    needs: create_terraform_backend
    runs-on: ubuntu-latest
    if: needs.create_terraform_backend.outputs.backend-setup == 'success'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.7.5'

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: |
        terraform plan -var="docker_compose_url=${{ env.DOCKER_COMPOSE_URL }}" \
                       -var="compose_file_url=${{ env.COMPOSE_FILE_URL }}" \
                       -var="nginx_conf_url=${{ env.NGINX_CONF_URL }}" \
                       -var="region=${{ env.AWS_DEFAULT_REGION }}" \
                       -out=plan.out
      working-directory: terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve "plan.out"
      working-directory: terraform
