name: 'Destroy Terraform Infrastructure'

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm destruction of Terraform-managed infrastructure'
        required: true
        default: 'type "destroy" here'

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change to Terraform directory
      run: cd terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.7.5'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_docker_compose_url: ${{ secrets.DOCKER_COMPOSE_URL }}
        TF_VAR_compose_file_url: ${{ secrets.COMPOSE_FILE_URL }}
        TF_VAR_nginx_conf_url: ${{ secrets.NGINX_CONF_URL }}

    - name: Confirm Destruction
      run: echo "Infrastructure destroyed successfully."
