name: Destroy Terraform Backend

on:
  workflow_dispatch:

jobs:
  destroy_terraform_backend:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
      AWS_BUCKET_NAME: the-block-crypto-state-bucket
      AWS_DYNAMO_TABLE: the-block-crypto-table

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run setup script
      run: |
        chmod +x ./terraform/scripts/destroy-tf-backend.sh
        ./terraform/scripts/destroy-tf-backend.sh
